export const InputType = {
    IMAGE64: 'IMAGE64',
    MULTI_IMAGE64: 'MULTI_IMAGE64',
    CHECKBOX: 'CHECKBOX',
    EDITOR: 'EDITOR',
    TEXT: 'TEXT',
    AREA: 'AREA',
    DATETIME: 'DATETIME',
    DATE: 'DATE',
    TIME: 'TIME',
    DROPDOWN: 'DROPDOWN',
};
